spring.application.name=LaptopShop

server.port=8086

spring.datasource.url=jdbc:postgresql://localhost:5435/mydb
spring.datasource.username=laptopuser
spring.datasource.password=laptopassword
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

cloudinary.api-secret = DkJ8BjHHBC2M4sNeSYyf_nHBae0
cloudinary.api-key = 913671482171219
cloudinary.cloud-name = dj5f5e5cx